export const userRows = [
  {
    userId: 'USR-001',
    id: 'alfatih',
    name: 'Al Fatih',
    username: 'alfatih',
    email: 'alfatih@pilargroup.id',
    phone: '+62 812 1000 1201',
    department: 'Information Technology',
    departmentId: 'DPT-IT',
    role: 'Frontend Developer',
    jobLevel: 'Staff',
    status: 'Active',
    statusKey: 'active',
    apps: ['MyTickets', 'Legal Docs', 'Tickets'],
    createdAt: '2026-01-10',
    updatedAt: '2026-04-29',
    lastActive: '2026-04-30 09:10',
  },
  {
    userId: 'USR-002',
    id: 'nabila',
    name: 'Nabila Putri',
    username: 'nabila',
    email: 'nabila@pilargroup.id',
    phone: '+62 812 1000 1202',
    department: 'Legal',
    departmentId: 'DPT-LGL',
    role: 'Legal Officer',
    jobLevel: 'Senior Staff',
    status: 'Active',
    statusKey: 'active',
    apps: ['Legal Docs', 'Tickets'],
    createdAt: '2026-01-18',
    updatedAt: '2026-04-24',
    lastActive: '2026-04-30 08:42',
  },
  {
    userId: 'USR-003',
    id: 'bagas',
    name: 'Bagas Pratama',
    username: 'bagas',
    email: 'bagas@pilargroup.id',
    phone: '+62 812 1000 1203',
    department: 'Finance',
    departmentId: 'DPT-FIN',
    role: 'Finance Reviewer',
    jobLevel: 'Supervisor',
    status: 'Pending',
    statusKey: 'pending',
    apps: ['Dashboard', 'Approval'],
    createdAt: '2026-02-03',
    updatedAt: '2026-04-22',
    lastActive: '2026-04-28 16:20',
  },
  {
    userId: 'USR-004',
    id: 'sarah',
    name: 'Sarah Wijaya',
    username: 'sarah',
    email: 'sarah@pilargroup.id',
    phone: '+62 812 1000 1204',
    department: 'Procurement',
    departmentId: 'DPT-PRC',
    role: 'Procurement Lead',
    jobLevel: 'Manager',
    status: 'Active',
    statusKey: 'active',
    apps: ['Vendor Portal', 'Approval', 'Tickets'],
    createdAt: '2026-02-12',
    updatedAt: '2026-04-25',
    lastActive: '2026-04-29 17:15',
  },
  {
    userId: 'USR-005',
    id: 'reza',
    name: 'Reza Mahendra',
    username: 'reza',
    email: 'reza@pilargroup.id',
    phone: '+62 812 1000 1205',
    department: 'Operations',
    departmentId: 'DPT-OPS',
    role: 'Operations Admin',
    jobLevel: 'Staff',
    status: 'Inactive',
    statusKey: 'inactive',
    apps: ['Dashboard'],
    createdAt: '2026-02-20',
    updatedAt: '2026-03-29',
    lastActive: '2026-03-27 11:05',
  },
  {
    userId: 'USR-006',
    id: 'dinda',
    name: 'Dinda Maharani',
    username: 'dinda',
    email: 'dinda@pilargroup.id',
    phone: '+62 812 1000 1206',
    department: 'Human Capital',
    departmentId: 'DPT-HC',
    role: 'HR Business Partner',
    jobLevel: 'Senior Staff',
    status: 'Active',
    statusKey: 'active',
    apps: ['Dashboard', 'User Access'],
    createdAt: '2026-03-01',
    updatedAt: '2026-04-27',
    lastActive: '2026-04-30 07:58',
  },
  {
    userId: 'USR-007',
    id: 'yusuf',
    name: 'Yusuf Hidayat',
    username: 'yusuf',
    email: 'yusuf@pilargroup.id',
    phone: '+62 812 1000 1207',
    department: 'Sales',
    departmentId: 'DPT-SLS',
    role: 'Sales Manager',
    jobLevel: 'Manager',
    status: 'Pending',
    statusKey: 'pending',
    apps: ['CRM', 'Dashboard'],
    createdAt: '2026-03-12',
    updatedAt: '2026-04-18',
    lastActive: '2026-04-18 13:30',
  },
  {
    userId: 'USR-008',
    id: 'mira',
    name: 'Mira Kartika',
    username: 'mira',
    email: 'mira@pilargroup.id',
    phone: '+62 812 1000 1208',
    department: 'Legal',
    departmentId: 'DPT-LGL',
    role: 'Contract Analyst',
    jobLevel: 'Staff',
    status: 'Active',
    statusKey: 'active',
    apps: ['Legal Docs', 'Tickets', 'Approval'],
    createdAt: '2026-03-22',
    updatedAt: '2026-04-29',
    lastActive: '2026-04-29 15:44',
  },
]