export const pageDetails = {
  '/documents': {
    title: 'Documents',
    eyebrow: 'Document Control',
    value: '8',
    detail: 'Dokumen legal yang membutuhkan validasi.',
  },
  '/Table': {
    title: 'Data Table',
    eyebrow: 'Table Template',
    value: '8',
    detail: 'Contoh komponen table dengan pencarian, detail row, action, dan pagination.',
  },
  '/TableActions': {
    title: 'Data Table Actions',
    eyebrow: 'Table Template',
    value: '8',
    detail: 'Contoh komponen table dengan kolom action inline untuk edit dan delete.',
  },
  '/TicketsOverview': {
    title: 'Tickets Overview',
    eyebrow: 'Ticket Analytics',
    value: '24',
    detail: 'Ringkasan status dan performa tiket legal.',
  },
  '/ProjectsOverview': {
    title: 'Projects Overview',
    eyebrow: 'Project Summary',
    value: '7',
    detail: 'Ringkasan proyek dan aktivitas terkait.',
  },
  '/Chart': {
    title: 'Chart',
    eyebrow: 'Visual Analytics',
    value: '5',
    detail: 'Kumpulan chart yang siap dipakai untuk visualisasi data.',
  },
  '/forms': {
    title: 'Forms',
    eyebrow: 'Component Template',
    value: '9',
    detail: 'Kumpulan komponen form yang siap dipakai untuk input data aplikasi.',
  },
  '/Forms': {
    title: 'Forms',
    eyebrow: 'Component Template',
    value: '9',
    detail: 'Kumpulan komponen form yang siap dipakai untuk input data aplikasi.',
  },
  '/frp': {
    title: 'FRP',
    eyebrow: 'Document Transaction',
    value: '0',
    detail: 'Daftar transaksi FRP.',
  },
  '/rp': {
    title: 'RP',
    eyebrow: 'Document Transaction',
    value: '0',
    detail: 'Daftar transaksi RP.',
  },
  '/Rp': {
    title: 'RP',
    eyebrow: 'Document Transaction',
    value: '0',
    detail: 'Daftar transaksi RP.',
  },
  '/Master/Vendor': {
    title: 'Vendor',
    eyebrow: 'Master Data',
    value: '0',
    detail: 'Master data vendor.',
  },
  '/Master/Banks': {
    title: 'Vendor Bank',
    eyebrow: 'Vendor Management',
    value: '0',
    detail: 'Master data vendor bank.',
  },
  '/Master/VendorBanksAccount': {
    title: 'Vendor Banks Account',
    eyebrow: 'Vendor Management',
    value: '0',
    detail: 'Master data vendor bank account.',
  },
  '/Master/Budget-type': {
    title: 'Budget Type',
    eyebrow: 'Budget Management',
    value: '0',
    detail: 'Master data budget type.',
  },
  '/Reports/TeamPerformance': {
    title: 'Team Performance',
    eyebrow: 'Reports',
    value: '4',
    detail: 'Performa bulanan setiap user lengkap dengan progress completed dan pending.',
  },
  '/users': {
    title: 'Users',
    eyebrow: 'Access Control',
    value: '16',
    detail: 'User internal yang memiliki akses ke aplikasi legal dengan berbagai peran dan status.',
  },
  '/settings': {
    title: 'Settings',
    eyebrow: 'Workspace',
    value: '5',
    detail: 'Konfigurasi utama untuk alur kerja legal.',
  },
  '/login': {
    title: 'Login',
    eyebrow: 'Session',
    value: '0',
    detail: 'Sesi pengguna sudah diarahkan keluar dari aplikasi.',
  },
}
